# Generated by Django 4.2.1 on 2023-05-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WD', 'Web Development'), ('DS', 'Data Secience'), ('AI', 'Artificial Intelligence'), ('GM', 'Game® Development')], max_length=100)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
