# Generated by Django 4.2.1 on 2023-05-16 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WD', 'Web Development'), ('DS', 'Data Science'), ('AI', 'Artificial Intelligence'), ('GM', 'Game® Development')], max_length=100),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(choices=[('AD', 'Adana'), ('ADI', 'Adıyaman'), ('AF', 'Afyonkarahisar'), ('AG', 'Ağrı'), ('AKS', 'Aksaray'), ('AM', 'Amasya'), ('ANK', 'Ankara'), ('ANT', 'Antalya'), ('ARD', 'Ardahan'), ('ART', 'Artvin'), ('AYI', 'Aydın'), ('BAL', 'Balıkesir'), ('BAR', 'Bartın'), ('BAT', 'Batman'), ('BAY', 'Bayburt'), ('BIL', 'Bilecik'), ('BIN', 'Bingöl'), ('BIT', 'Bitlis'), ('BOL', 'Bolu'), ('BRD', 'Burdur'), ('BRS', 'Bursa'), ('ÇAN', 'Çanakkale'), ('ÇAN', 'Çankırı'), ('ÇOR', 'Çorum'), ('DEN', 'Denizli'), ('DIY', 'Diyarbakır'), ('DÜZ', 'Düzce'), ('ED', 'Edirne'), ('ELA', 'Elazığ'), ('ERZ', 'Erzincan'), ('ERZ', 'Erzurum'), ('ESK', 'Eskişehir'), ('GAZ', 'Gaziantep'), ('GIR', 'Giresun'), ('GMS', 'Gümüşhane'), ('HAK', 'Hakkari'), ('HAT', 'Hatay'), ('IGD', 'Iğdır'), ('ISPA', 'Isparta'), ('IST', 'Istanbul'), ('IZM', 'Izmir'), ('KAHR', 'Kahramanmaraş'), ('KARA', 'Karabük'), ('KARAM', 'Karaman'), ('KARS', 'Kars'), ('KAS', 'Kastamonu'), ('KAY', 'Kayseri'), ('KIL', 'Kilis'), ('KIRIK', 'Kırıkkale'), ('KIRKL', 'Kırklareli'), ('KIRSE', 'Kırşehir'), ('KOC', 'Kocaeli'), ('KON', 'Konya'), ('KÜTA', 'Kütahya'), ('MAL', 'Malatya'), ('MAN', 'Manisa'), ('MARD', 'Mardin'), ('MERS', 'Mersin'), ('MUĞ', 'Muğla'), ('MUŞ', 'Muş'), ('NEVŞ', 'Nevşehir'), ('NİĞD', 'Niğde'), ('ORDU', 'Ordu'), ('OSM', 'Osmaniye'), ('RIZ', 'Rize'), ('SAKA', 'Sakarya'), ('SAM', 'Samsun'), ('SİIR', 'Siirt'), ('SİNA', 'Sinop'), ('ŞIRN', 'Şırnak'), ('SİV', 'Sivas'), ('TEK', 'Tekirdağ'), ('TOK', 'Tokat'), ('TRA', 'Trabzon'), ('TUN', 'Tunceli'), ('URF', 'Urfa'), ('UŞA', 'Uşak'), ('VAN', 'Van'), ('YAL', 'Yalova'), ('YOZ', 'Yozgat'), ('ZON', 'Zonguldak')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
