# Generated by Django 4.2.1 on 2023-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_zip_code_customer_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('AD', 'Adana'), ('ADI', 'Adıyaman'), ('AF', 'Afyonkarahisar'), ('AG', 'Ağrı'), ('AKS', 'Aksaray'), ('AM', 'Amasya'), ('ANK', 'Ankara'), ('ANT', 'Antalya'), ('ARD', 'Ardahan'), ('ART', 'Artvin'), ('AYI', 'Aydın'), ('BAL', 'Balıkesir'), ('BAR', 'Bartın'), ('BAT', 'Batman'), ('BAY', 'Bayburt'), ('BIL', 'Bilecik'), ('BIN', 'Bingöl'), ('BIT', 'Bitlis'), ('BOL', 'Bolu'), ('BRD', 'Burdur'), ('BRS', 'Bursa'), ('ÇAN', 'Çanakkale'), ('ÇAN', 'Çankırı'), ('ÇOR', 'Çorum'), ('DEN', 'Denizli'), ('DIY', 'Diyarbakır'), ('DÜZ', 'Düzce'), ('ED', 'Edirne'), ('ELA', 'Elazığ'), ('ERZ', 'Erzincan'), ('ERZ', 'Erzurum'), ('ESK', 'Eskişehir'), ('GAZ', 'Gaziantep'), ('GIR', 'Giresun'), ('GMS', 'Gümüşhane'), ('HAK', 'Hakkari'), ('HAT', 'Hatay'), ('IGD', 'Iğdır'), ('ISPA', 'Isparta'), ('IST', 'Istanbul'), ('IZM', 'Izmir'), ('KAHR', 'Kahramanmaraş'), ('KARA', 'Karabük'), ('KARAM', 'Karaman'), ('KARS', 'Kars'), ('KAS', 'Kastamonu'), ('KAY', 'Kayseri'), ('KIL', 'Kilis'), ('KIRIK', 'Kırıkkale'), ('KIRKL', 'Kırklareli'), ('KIRSE', 'Kırşehir'), ('KOC', 'Kocaeli'), ('KON', 'Konya'), ('KÜTA', 'Kütahya'), ('MAL', 'Malatya'), ('MAN', 'Manisa'), ('MARD', 'Mardin'), ('MERS', 'Mersin'), ('MUĞ', 'Muğla'), ('MUŞ', 'Muş'), ('NEVŞ', 'Nevşehir'), ('NİĞD', 'Niğde'), ('ORDU', 'Ordu'), ('OSM', 'Osmaniye'), ('RIZ', 'Rize'), ('SAKA', 'Sakarya'), ('SAM', 'Samsun'), ('SİIR', 'Siirt'), ('SİNA', 'Sinop'), ('ŞIRN', 'Şırnak'), ('SİV', 'Sivas'), ('TEK', 'Tekirdağ'), ('TOK', 'Tokat'), ('TRA', 'Trabzon'), ('TUN', 'Tunceli'), ('URF', 'Urfa'), ('UŞA', 'Uşak'), ('VAN', 'Van'), ('YAL', 'Yalova'), ('YOZ', 'Yozgat'), ('ZON', 'Zonguldak')], max_length=50),
        ),
    ]
